
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS service VARCHAR(80) DEFAULT NULL;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE shipments MODIFY COLUMN status VARCHAR(60) DEFAULT 'waiting_seller';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_address_id BIGINT DEFAULT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tracking_number VARCHAR(120) DEFAULT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivered_at DATETIME DEFAULT NULL;
ALTER TABLE invoices ADD INDEX IF NOT EXISTS idx_invoice_number (invoice_number);
